name: Open Rubric CamtasiaWin PR Dispatcher Action Initiator

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  action_initiator:
    if: ${{ startsWith(github.head_ref, 'rubricTranslation/') && github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: PING
        run: |
          curl -L \
          -X POST \
          https://api.github.com/repos/mgoblue/Two/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MGOBLUE_GITHUB_TOKEN }}" \
          -d '{"event_type": "ping", "client_payload": { "repository": "${{ github.repository }}", "branch": "${{ github.head_ref }}" }}'
