name: Action Initiator

on:
  workflow_dispatch:
  pull_request:
    branches:
      - eugin/*
    types:
      - closed
  

jobs:
  action_initiator:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request.merged }}
    steps:
      - name: PING
        run: |
          curl -L \
          -X POST \
          https://api.github.com/repos/mgoblue/Two/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MGOBLUE_GITHUB_TOKEN }}" \
          -d '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
